# Generated by Django 5.2.7 on 2025-10-12 02:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Game Name')),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
            },
        ),
        migrations.CreateModel(
            name='TournamentFormat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Format Name')),
                ('team_size', models.PositiveSmallIntegerField(verbose_name='Players per Team')),
                ('description', models.TextField(blank=True, verbose_name='Format Description')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='formats', to='tournaments.game', verbose_name='Associated Game')),
            ],
            options={
                'verbose_name': 'Tournament Format',
                'verbose_name_plural': 'Tournament Formats',
                'unique_together': {('game', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tournament_name', models.CharField(max_length=255, verbose_name='Tournament Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('prize_pool', models.PositiveIntegerField(default=0, verbose_name='Prize Pool (IDR)')),
                ('banner', models.URLField(blank=True, null=True, verbose_name='Banner Image URL')),
                ('team_count', models.PositiveIntegerField(default=0, verbose_name='Current Team Count')),
                ('team_maximum_count', models.PositiveIntegerField(verbose_name='Maximum Team Capacity')),
                ('tournament_format', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tournaments', to='tournaments.tournamentformat', verbose_name='Tournament Format')),
            ],
            options={
                'verbose_name': 'Tournament',
                'verbose_name_plural': 'Tournaments',
                'ordering': ['start_date', 'tournament_name'],
            },
        ),
    ]
