# Generated by Django 5.2.7 on 2025-10-12 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='team_count',
        ),
    ]
