# Generated by Django 5.2.7 on 2025-10-22 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_alter_tournament_options_remove_tournament_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentformat',
            name='description',
        ),
    ]
