# Generated by Django 5.2.7 on 2025-10-23 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_remove_tournamentformat_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='team_maximum_count',
            field=models.PositiveIntegerField(verbose_name='Maximum Team Entry'),
        ),
    ]
