# Generated by Django 5.2.7 on 2025-10-24 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_alter_tournament_team_maximum_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # This migration was merged into 0006_alter_tournament_options_tournament_created_at_and_more
        # and its AddField operation would duplicate the same column. Leave as no-op to preserve
        # migration history without executing a duplicate AddField.
    ]
