# Generated by Django 5.2.7 on 2025-10-24 11:06

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_alter_tournament_team_maximum_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournament',
            options={'ordering': ['-created_at', 'tournament_date', 'tournament_name'], 'verbose_name': 'Tournament', 'verbose_name_plural': 'Tournaments'},
        ),
        migrations.AddField(
            model_name='tournament',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournament',
            name='organizer',
            field=models.ForeignKey(default=1, limit_choices_to={'role': 'organizer'}, on_delete=django.db.models.deletion.PROTECT, related_name='organized_tournaments', to=settings.AUTH_USER_MODEL, verbose_name='Organizer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournament',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.CreateModel(
            name='TournamentParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('disqualified', 'Disqualified')], default='registered', max_length=20, verbose_name='Status')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='Registration Date')),
                ('team_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Team Name')),
                ('participant', models.ForeignKey(limit_choices_to={'role': 'user'}, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_participations', to=settings.AUTH_USER_MODEL, verbose_name='Participant')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_records', to='tournaments.tournament', verbose_name='Tournament')),
            ],
            options={
                'verbose_name': 'Tournament Participant',
                'verbose_name_plural': 'Tournament Participants',
                'ordering': ['registered_at'],
                'unique_together': {('tournament', 'participant')},
            },
        ),
        migrations.AddField(
            model_name='tournament',
            name='participants',
            field=models.ManyToManyField(related_name='participated_tournaments', through='tournaments.TournamentParticipant', to=settings.AUTH_USER_MODEL, verbose_name='Participants'),
        ),
    ]
