# Generated by Django 5.2.7 on 2025-10-24 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_alter_tournament_options_tournament_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='organizer',
            field=models.ForeignKey(limit_choices_to={'role': ['organizer', 'admin']}, on_delete=django.db.models.deletion.PROTECT, related_name='organized_tournaments', to=settings.AUTH_USER_MODEL, verbose_name='Organizer'),
        ),
    ]
