# Generated by Django 5.2.7 on 2025-10-26 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0007_alter_tournament_organizer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='tournament_format',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='tournaments.tournamentformat', verbose_name='Tournament Format'),
        ),
    ]
