# Generated by Django 5.2.7 on 2025-10-25 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_alter_tournament_options_tournament_created_at_and_more'),
        ('tournaments', '0007_alter_tournament_organizer'),
    ]

    operations = [
    ]
