# Generated by Django 5.2.7 on 2025-10-25 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_tournament_organizer'),
        ('tournaments', '0008_merge_20251025_0840'),
    ]

    operations = [
    ]
