# Generated by Django 5.2.7 on 2025-10-26 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0008_alter_tournament_tournament_format'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='organizer',
            field=models.ForeignKey(limit_choices_to={'role': ['organizer', 'admin']}, on_delete=django.db.models.deletion.CASCADE, related_name='organized_tournaments', to=settings.AUTH_USER_MODEL, verbose_name='Organizer'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_format',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tournaments', to='tournaments.tournamentformat', verbose_name='Tournament Format'),
        ),
    ]
