# Generated by Django 5.2.7 on 2025-10-26 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0009_alter_tournament_organizer_and_more'),
        ('tournaments', '0009_merge_20251025_1110'),
    ]

    operations = [
    ]
