# Generated by Django 5.2.7 on 2025-10-23 14:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournament_registration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tournament_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='tournament_registration.tournamentregistration')),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_invites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('user_account', 'tournament_registration'), name='unique_pending_invite')],
            },
        ),
    ]
