# Generated by Django 5.2.7 on 2025-10-12 10:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('password_hash', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('user', 'User'), ('organizer', 'Organizer'), ('admin', 'Admin')], default='user', max_length=10)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'User Account',
                'verbose_name_plural': 'User Accounts',
                'ordering': ['-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('active', True)), fields=('username',), name='unique_active_username'), models.UniqueConstraint(condition=models.Q(('active', True)), fields=('email',), name='unique_active_email')],
            },
        ),
    ]
