# Generated by Django 5.2.7 on 2025-10-22 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0002_alter_useraccount_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='profile_image',
            field=models.CharField(default='avatar1', help_text='Pilihan: avatar1, avatar2, avatar3', max_length=50),
        ),
    ]
