# Generated by Django 5.2.7 on 2025-10-12 11:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game_account', '0001_initial'),
        ('tournaments', '0002_remove_tournament_team_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=100, verbose_name='Team Name')),
                ('status', models.CharField(choices=[('invalid', 'Invalid'), ('valid', 'Valid'), ('registered', 'Registered')], default='invalid', max_length=31, verbose_name='Registration Status')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='tournaments.tournament', verbose_name='Associated Tournament')),
            ],
            options={
                'verbose_name': 'Tournament Registration',
                'verbose_name_plural': 'Tournament Registrations',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_leader', models.BooleanField(default=False)),
                ('game_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joined_teams', to='game_account.gameaccount', verbose_name='Associated Game Account')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='tournament_registration.tournamentregistration', verbose_name='Associated Team')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
            },
        ),
        migrations.AddConstraint(
            model_name='tournamentregistration',
            constraint=models.UniqueConstraint(fields=('tournament', 'team_name'), name='unique_team_name_in_tournament'),
        ),
    ]
