# Generated by Django 5.2.7 on 2025-10-25 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_account', '0001_initial'),
        ('tournament_registration', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='teammember',
            constraint=models.UniqueConstraint(condition=models.Q(('is_leader', True)), fields=('team',), name='unique_leader_per_team'),
        ),
    ]
